kotlin.code.style=official
# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.217-java25
neo_version_range=[21,)
loader_version_range=[4.0,)
# Mod information
mod_group_id=org.bread_experts_group
mod_id=breadmod
mod_name=Bread Mod
mod_license=GNU LGPL 3.0
mod_version=1.5.1
mod_authors=Logan McLean (ttttdoy), Miko Elbrecht (meownium)
mod_description=The Breadmod.