# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[4,)" # Require at least 4.x
license="${mod_license}"

[[mods]]
    modId="breadmod"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    logoFile="logo.png"
[[dependencies.breadmod]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.10,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version_range}"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.breadmod]]
    modId="jade"
    mandatory=false
    versionRange="${jade_version_range}"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.breadmod]]
    modId="mekanism"
    mandatory=false
    versionRange="${mekanism_version_range}"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="projecte"
    mandatory=false
    versionRange="${projecte_version_range}"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="create"
    mandatory=false
    versionRange="${create_version_range}"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.breadmod]]
    modId="breadmodadv"
    mandatory=false
    versionRange="0.0.1"
    ordering="AFTER"
    side="BOTH"