package breadmod.client.screen.tool_gun.creator

import breadmod.item.tool_gun.IToolGunMode.Companion.BASE_TOOL_GUN_DATA_PATH
import breadmod.item.tool_gun.ToolGunItem
import breadmod.item.tool_gun.mode.creator.ToolGunCreatorMode
import breadmod.menu.item.ToolGunCreatorMenu
import breadmod.util.gui.SerializedScreenFactory
import breadmod.util.gui.widget.BackgroundWidget
import breadmod.util.gui.widget.ContainerWidget
import breadmod.util.gui.widget.TextWidget
import breadmod.util.render.rgMinecraft
import net.minecraft.network.chat.Component
import net.minecraft.world.entity.EntityType
import net.minecraft.world.entity.player.Inventory
import java.awt.Color

/**
 * Factory to create the spawn menu for the [ToolGunItem]'s [ToolGunCreatorMode].
 * @author Miko Elbrecht, Logan McLean (first iteration)
 * @since 1.0.0
 */
object ToolGunCreatorSpawnMenuFactory : SerializedScreenFactory<ToolGunCreatorMenu>(
    BASE_TOOL_GUN_DATA_PATH.resolve("creator/screens/spawn_menu.json")
) {
    internal val ENTITY_PATH = BASE_TOOL_GUN_DATA_PATH.resolve("creator/entity.json").toFile()

    internal val loadedEntity: ToolGunCreatorMode.CreatorEntity = ToolGunCreatorMode.CreatorEntity(
        null,
        EntityType.PIG,
        20.0,
        0.25,
        mutableMapOf(),
        40.0
    )
    internal var lastSaved: String? = null

    override fun default(): ContainerWidget = ContainerWidget(
        600, 600,
        0, 0,
        0f,
        Component.empty(),
        mutableMapOf(
//            ContainerWidget(
//                200, 600,
//                0, 0,
//                Math.toRadians(0.0).toFloat(),
//                Component.empty(),
//                mutableMapOf(
//                    TextWidget(
//                        0, 0,
//                        200, 600,
//                        Component.literal(
//                            @Suppress("LongLine")
//                            "BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD BREADMOD"
//                        ),
//                        Color(1f, 1f, 1f, 0.5f),
//                        pCentering = TextWidget.CenteringType.CENTER_RECT,
//                        pWrapping = TextWidget.WrappingType.WRAP_VERTICAL,
//                        pNoScissor = true
//                    ) to 0.0
//                )
//            ) to 0.0,
            BackgroundWidget.SolidColorBackgroundWidget(
                28, 28,
                304, 144,
                Color(0f, 0f, 0f, 0.1f)
            ) to 0.0,
            BackgroundWidget.SolidColorBackgroundWidget(
                29, 29,
                302, 142,
                Color(0f, 0f, 0f, 0.1f)
            ) to 0.1,
            TextWidget(
                31, 31,
                300, rgMinecraft.font.lineHeight,
                Component.literal("Test"),
                pCentering = TextWidget.CenteringType.NONE
            ) to 0.2
        )
    )

    override fun create(pMenu: ToolGunCreatorMenu, pInventory: Inventory, pTitle: Component): ToolGunCreatorSerializedScreen =
        ToolGunCreatorSerializedScreen(
            pMenu,
            pInventory,
            pTitle,
            getRootWidget()
        )
}