# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[4,)" # Require at least 4.x
license="${mod_license}"

[[mods]]
    modId="breadmodadv"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    logoFile="logo.png"
[[dependencies.breadmodadv]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.breadmodadv]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.10,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.breadmodadv]]
    modId = "breadmod"
    mandatory=true
    versionRange="${breadmod_version_range}"
    ordering="BEFORE"
    side="BOTH"