modLoader = "kotlinforforge"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "breadmod"
version = "${version}"
displayName = "Bread Mod"
authors = "2!!!"
description = '''
the breadmod...
'''
#logoFile = ""

[[dependencies.breadmod]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breadmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breadmod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.breadmod]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "breadmod.mixins.json"
