/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class breadmod_natives_windows_ACrasherWindows */

#ifndef _Included_breadmod_natives_windows_ACrasherWindows
#define _Included_breadmod_natives_windows_ACrasherWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     breadmod_natives_windows_ACrasherWindows
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_breadmod_natives_windows_ACrasherWindows_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
