name: Mod Compile Checks

on:
  push:
    branches: [ "1.20.1" ]
  pull_request:
    branches: [ "1.20.1" ]

jobs:
  data-generation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Make gradlew executable # BANDAID FIX
      run: chmod +x ./gradlew
    - name: Run Data Generation (Server, Client)
      run: ./gradlew runData
  release-jar-snapshot:
    needs: [data-generation]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Make gradlew executable # BANDAID FIX
      run: chmod +x ./gradlew
    - name: Build JAR file
      run: ./gradlew build
    - name: TODO Publish
      run: ls build
