name: Kotlin Subproject Remote Runs

on:
  push:
    branches: [ "1.20.1" ]
    paths: [".github/workflows/kotlinSubprojRun.yml","virtualmachine/**"]
  pull_request:
    branches: [ "1.20.1" ]
    paths: [".github/workflows/kotlinSubprojRun.yml","virtualmachine/**"]

jobs:
  release-jar-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Run Program
      run: ./gradlew run
